import { t } from "../../../js/i18n.js";
import { formatBytes, moveArrayItem } from "../../shared/file.js";
import { ACCEPTED_IMAGE_TYPES, selectImageQueueFiles, validateImageSignature } from "../../shared/image.js";
import { IMAGE_FORMATS } from "../../shared/image-output.js";
import { downloadBlob, requestSaveHandle, writeBlobToHandle } from "../../shared/save.js";
import { compressImages, createCompressionPlan } from "./compressor.js";

const elements = {
  input: document.querySelector("#file-input"), dropZone: document.querySelector("#drop-zone"), list: document.querySelector("#image-list"), empty: document.querySelector("#queue-empty"), count: document.querySelector("#image-count"), add: document.querySelector("#add-images"), clear: document.querySelector("#clear-images"), compress: document.querySelector("#compress-images"), form: document.querySelector("#compression-settings"), format: document.querySelector("#output-format"), quality: document.querySelector("#quality"), qualityField: document.querySelector("#quality-field"), qualityValue: document.querySelector("#quality-value"), progress: document.querySelector("#compression-progress"), status: document.querySelector("#tool-status"), results: document.querySelector("#compression-results"), resultList: document.querySelector("#result-list"), summary: document.querySelector("#result-summary"),
};
const state = { items: [], busy: false, status: null, result: null };
elements.input.accept = ACCEPTED_IMAGE_TYPES;
const message = (key, values = {}) => Object.entries(values).reduce((text, [name, value]) => text.replaceAll(`{${name}}`, String(value)), t(key));
function setStatus(key, values = {}, tone = "neutral") { state.status = key ? { key, values, tone } : null; elements.status.textContent = key ? message(key, values) : ""; elements.status.dataset.tone = tone; }
function invalidateResults(changed = false) { if (changed && state.result) setStatus("imageCompressor.status.settingsChanged"); state.result = null; elements.results.hidden = true; elements.resultList.replaceChildren(); elements.summary.textContent = ""; }
function rejectionReason(code) { return message(({ UNSUPPORTED_IMAGE: "imageToPdf.errors.unsupported", IMAGE_FILE_TOO_LARGE: "imageToPdf.errors.fileTooLarge", IMAGE_QUEUE_FILES_EXCEEDED: "imageToPdf.errors.queueFiles", IMAGE_SIGNATURE_INVALID: "imageToPdf.errors.signature", IMAGE_QUEUE_BYTES_EXCEEDED: "imageToPdf.errors.queueBytes" })[code] || "imageToPdf.errors.unsupported"); }
function setRejectedStatus(added, rejected) { state.status = { added, rejected, tone: "warning" }; const reasons = rejected.map(({ file, code }) => message("imageToPdf.status.rejectedItem", { name: file.name || "file", reason: rejectionReason(code) })).join("; "); elements.status.textContent = message("imageToPdf.status.addedWithReasons", { added, reasons }); elements.status.dataset.tone = "warning"; }
function actionButton(action, labelKey, symbol, disabled = false) { const button = document.createElement("button"); button.type = "button"; button.className = `queue-action queue-action--${action}`; button.dataset.action = action; button.setAttribute("aria-label", t(labelKey)); button.title = t(labelKey); button.textContent = symbol; button.disabled = disabled || state.busy; return button; }

function updateFormatSettings() { const originalHasLossy = !state.items.length || state.items.some((item) => item.format !== "png"); const showQuality = elements.format.value !== "png" && (elements.format.value !== "original" || originalHasLossy); elements.qualityField.hidden = !showQuality; elements.quality.disabled = state.busy || !showQuality; }
function renderQueue() { elements.list.replaceChildren(); elements.empty.hidden = state.items.length > 0; elements.count.textContent = message("imageToPdf.queue.count", { count: state.items.length }); elements.clear.disabled = state.busy || !state.items.length; elements.compress.disabled = state.busy || !state.items.length; elements.add.disabled = state.busy; elements.input.disabled = state.busy; elements.format.disabled = state.busy; state.items.forEach((item, index) => { const row = document.createElement("li"); row.className = "queue-item"; row.dataset.id = item.id; const thumbnail = document.createElement("img"); thumbnail.className = "queue-thumbnail"; thumbnail.src = item.url; thumbnail.alt = message("imageToPdf.queue.previewAlt", { name: item.file.name }); const details = document.createElement("div"); details.className = "queue-details"; const name = document.createElement("strong"); name.className = "queue-name"; name.textContent = item.file.name; name.title = item.file.name; const meta = document.createElement("span"); meta.className = "queue-meta"; meta.textContent = message("imageCompressor.queue.meta", { size: formatBytes(item.file.size), format: item.format.toUpperCase(), position: index + 1 }); details.append(name, meta); const actions = document.createElement("div"); actions.className = "queue-actions"; actions.append(actionButton("up", "imageToPdf.queue.moveUp", "↑", index === 0), actionButton("down", "imageToPdf.queue.moveDown", "↓", index === state.items.length - 1), actionButton("remove", "imageToPdf.queue.remove", "×")); row.append(thumbnail, details, actions); elements.list.append(row); }); updateFormatSettings(); }

async function addFiles(files) { const { accepted, rejected } = await selectImageQueueFiles(state.items.map((item) => item.file), files); for (const file of accepted) state.items.push({ id: crypto.randomUUID?.() || `${Date.now()}-${Math.random()}`, file, format: await validateImageSignature(file), url: URL.createObjectURL(file) }); invalidateResults(); if (rejected.length) setRejectedStatus(accepted.length, rejected); else if (accepted.length) setStatus("imageToPdf.status.added", { count: accepted.length }, "success"); else setStatus("imageToPdf.errors.unsupported", {}, "error"); renderQueue(); }
function removeItem(index) { const [item] = state.items.splice(index, 1); if (item) URL.revokeObjectURL(item.url); invalidateResults(); setStatus("imageToPdf.status.removed"); renderQueue(); }
function moveItem(index, offset) { const next = moveArrayItem(state.items, index, offset); if (next < 0) return; invalidateResults(); setStatus("imageToPdf.status.reordered"); renderQueue(); elements.list.querySelector(`[data-id="${state.items[next].id}"] [data-action="${offset < 0 ? "up" : "down"}"]`)?.focus(); }
function clearItems() { state.items.forEach((item) => URL.revokeObjectURL(item.url)); state.items.length = 0; elements.input.value = ""; invalidateResults(); setStatus("imageToPdf.status.cleared"); renderQueue(); }
function changeText(metrics) { return metrics.larger ? message("imageCompressor.results.increased", { percent: Math.abs(metrics.reductionPercent).toFixed(1), bytes: formatBytes(Math.abs(metrics.difference)) }) : message("imageCompressor.results.saved", { percent: metrics.reductionPercent.toFixed(1), bytes: formatBytes(metrics.difference) }); }
function metric(labelKey, value) { const wrapper = document.createElement("span"); wrapper.className = "compression-result__metric"; const label = document.createElement("span"); label.textContent = t(labelKey); const strong = document.createElement("strong"); strong.textContent = value; wrapper.append(label, strong); return wrapper; }
function renderResults(result) { state.result = result; elements.resultList.replaceChildren(); result.results.forEach((entry) => { const item = document.createElement("li"); item.className = "compression-result"; const name = document.createElement("strong"); name.className = "compression-result__name"; name.textContent = entry.name; name.title = entry.name; const change = metric("imageCompressor.results.change", changeText(entry)); change.classList.add("compression-result__change"); item.append(name, metric("imageCompressor.results.original", formatBytes(entry.originalSize)), metric("imageCompressor.results.result", formatBytes(entry.resultSize)), change); elements.resultList.append(item); }); elements.summary.textContent = message(result.aggregate.larger ? "imageCompressor.results.aggregateIncreased" : "imageCompressor.results.aggregateSaved", { original: formatBytes(result.aggregate.originalSize), result: formatBytes(result.aggregate.resultSize), bytes: formatBytes(Math.abs(result.aggregate.difference)), percent: Math.abs(result.aggregate.reductionPercent).toFixed(1) }); elements.results.hidden = false; }
function errorMessage(error) { return message(({ NO_FILES: "imageCompressor.errors.noFiles", IMAGE_FORMAT_INVALID: "imageCompressor.errors.format", IMAGE_DECODE_FAILED: "imageToPdf.errors.decode", IMAGE_DIMENSION_EXCEEDED: "imageToPdf.errors.dimension", IMAGE_PIXELS_EXCEEDED: "imageToPdf.errors.pixels", IMAGE_JOB_PIXELS_EXCEEDED: "imageCompressor.errors.jobPixels", COMPRESSION_SIZE_INVALID: "imageCompressor.errors.size", CANVAS_UNAVAILABLE: "imageConverter.errors.canvas", IMAGE_ENCODER_FAILED: "imageConverter.errors.encoder", ARCHIVE_LIBRARY_UNAVAILABLE: "imageConverter.errors.archiveLibrary", ARCHIVE_GENERATION_FAILED: "imageConverter.errors.archive" })[error.code] || "imageCompressor.errors.failure", { name: error.fileName || "" }); }

async function compressQueue() { if (!state.items.length || state.busy) { setStatus("imageCompressor.errors.noFiles", {}, "error"); return; } const files = state.items.map((item) => item.file); const options = { files, sourceFormats: state.items.map((item) => item.format), outputFormat: elements.format.value, quality: Number(elements.quality.value) }; try { createCompressionPlan(options); } catch (error) { elements.status.textContent = errorMessage(error); elements.status.dataset.tone = "error"; return; } state.busy = true; elements.progress.hidden = false; elements.progress.max = files.length; elements.progress.value = 0; invalidateResults(); setStatus("imageCompressor.status.compressing"); renderQueue(); try { const result = await compressImages({ files, outputFormat: options.outputFormat, quality: options.quality, JSZip: window.JSZip, onProgress(completed, total) { elements.progress.value = completed; setStatus("imageCompressor.status.progress", { completed, total }); } }); renderResults(result); const multiple = files.length > 1; const outputType = multiple ? "application/zip" : IMAGE_FORMATS[result.plan.formats[0]].mimeType; const extension = multiple ? ".zip" : `.${IMAGE_FORMATS[result.plan.formats[0]].extension}`; let handle = null; if ("showSaveFilePicker" in window) { try { handle = await requestSaveHandle(window, { suggestedName: result.filename, description: t(multiple ? "imageCompressor.settings.zipFile" : "imageCompressor.settings.imageFile"), mimeType: outputType, extension }); } catch (error) { if (error.name === "AbortError") { setStatus("imageCompressor.status.saveCancelled"); return; } throw error; } } if (handle) await writeBlobToHandle(handle, result.blob); else downloadBlob(result.blob, result.filename); setStatus(handle ? "imageCompressor.status.saved" : "imageCompressor.status.downloaded", { name: result.filename, count: result.entries.length }, "success"); } catch (error) { console.error("Image compression failed", error); elements.status.textContent = errorMessage(error); elements.status.dataset.tone = "error"; state.status = null; } finally { state.busy = false; elements.progress.hidden = true; renderQueue(); } }

elements.add.addEventListener("click", () => elements.input.click()); elements.input.addEventListener("change", (event) => { void addFiles([...event.target.files]); elements.input.value = ""; }); elements.clear.addEventListener("click", clearItems); elements.compress.addEventListener("click", compressQueue); elements.format.addEventListener("change", () => { invalidateResults(true); updateFormatSettings(); }); elements.quality.addEventListener("input", () => { elements.qualityValue.textContent = `${Math.round(Number(elements.quality.value) * 100)}%`; invalidateResults(true); }); elements.list.addEventListener("click", (event) => { const button = event.target.closest("button[data-action]"); if (!button) return; const index = state.items.findIndex((item) => item.id === button.closest("[data-id]").dataset.id); if (button.dataset.action === "remove") removeItem(index); if (button.dataset.action === "up") moveItem(index, -1); if (button.dataset.action === "down") moveItem(index, 1); }); ["dragenter", "dragover"].forEach((type) => elements.dropZone.addEventListener(type, (event) => { event.preventDefault(); if (!state.busy) elements.dropZone.dataset.dragging = "true"; })); ["dragleave", "drop"].forEach((type) => elements.dropZone.addEventListener(type, (event) => { event.preventDefault(); delete elements.dropZone.dataset.dragging; })); elements.dropZone.addEventListener("drop", (event) => { if (!state.busy) void addFiles([...event.dataTransfer.files]); }); document.addEventListener("securetools:languagechange", () => { renderQueue(); if (state.result) renderResults(state.result); if (state.status?.rejected) setRejectedStatus(state.status.added, state.status.rejected); else if (state.status) setStatus(state.status.key, state.status.values, state.status.tone); }); window.addEventListener("beforeunload", () => state.items.forEach((item) => URL.revokeObjectURL(item.url))); elements.qualityValue.textContent = `${Math.round(Number(elements.quality.value) * 100)}%`; renderQueue();
