const copy = {
  eyebrow: "Local PDF OCR", title: "PDF to Text", description: "Recognize editable text from every page or a selected page range without uploading your PDF.",
  drop: { title: "Add one PDF", description: "Drop a PDF here or use the picker.", choose: "Choose PDF", localTitle: "Processed locally.", localBody: "The PDF, rendered pages, and recognized text stay on this device.", privacyLink: "How privacy works" },
  source: { title: "Source PDF", empty: "No PDF selected yet.", selectedLabel: "Selected source PDF", meta: "{pages} pages · {size}", replace: "Replace PDF", remove: "Remove PDF" },
  warning: { large: "Large PDFs can take a while. Keep this tab open while local OCR runs." },
  settings: { title: "Recognition", pages: "Pages", all: "All pages", selected: "Selected pages", range: "Page range", rangePlaceholder: "1, 3-5", rangeHelp: "Use commas and ranges, such as 1, 3-5.", language: "Text language", english: "English", korean: "Korean", combined: "English + Korean", recognize: "Recognize text", cancel: "Cancel", progress: "Recognition progress" },
  result: { title: "Recognized text", description: "Review and edit each page before copying or downloading it.", searchableHint: "The searchable PDF uses the original OCR layout and preserves the visible PDF pages.", page: "Page {page}", pageLabel: "Editable recognized text for page {page}", copyPage: "Copy page", copyAll: "Copy all", download: "Download TXT", downloadSearchable: "Download searchable PDF" },
  status: { preparing: "Preparing the PDF locally…", ready: "PDF ready. Choose pages and a language to begin.", cancelled: "Operation cancelled. The PDF remains ready.", success: "Recognition complete. You can edit every page.", building: "Building the searchable PDF locally…", copied: "All recognized text copied.", pageCopied: "Page {page} copied.", downloaded: "Downloaded {name}.", searchableDownloaded: "Downloaded {name}." },
  progress: { starting: "Starting local recognition…", loading: "Loading the PDF locally…", "rendering-page": "Rendering page {page} of {total}…", "recognizing-page": "Recognizing page {page} of {total}… {percent}%", building: "Building text layer for page {page} of {total}…", saving: "Saving the searchable PDF locally…", complete: "Finishing recognition…" },
  errors: { oneFile: "Choose exactly one PDF.", UNSUPPORTED_PDF: "Choose a valid PDF file.", UNREADABLE_PDF: "This PDF could not be read.", ENCRYPTED_PDF: "Password-protected PDFs are not supported.", PDF_HAS_NO_PAGES: "This PDF has no pages.", PAGE_RANGE_REQUIRED: "Enter at least one page.", PAGE_RANGE_INVALID: "Enter pages as numbers and ranges, such as 1, 3-5.", PAGE_RANGE_REVERSED: "A page range cannot run backwards.", PAGE_OUT_OF_RANGE: "One or more pages are outside this PDF.", PDF_OCR_PAGE_DUPLICATE: "Choose each page only once.", PDF_OCR_RENDER_DIMENSION_EXCEEDED: "A page is too large to render safely.", PDF_OCR_RENDER_PIXELS_EXCEEDED: "A page is too large to render safely.", PDF_OCR_FAILED: "Recognition failed. Try again or choose another PDF.", PDF_LIBRARY_UNAVAILABLE: "The local PDF reader is unavailable.", SEARCHABLE_PDF_FONT_UNAVAILABLE: "The local Korean font could not be loaded.", SEARCHABLE_PDF_LAYOUT_REQUIRED: "Run recognition again to create a searchable PDF.", SEARCHABLE_PDF_FAILED: "The searchable PDF could not be created. Try again.", copy: "The text could not be copied. Select it manually and copy it.", download: "The text file could not be downloaded." },
};
const localized = {
  en: { title: "PDF to Text", description: copy.description, toolName: "PDF to Text OCR", category: "Extract editable text from PDF pages with local English and Korean OCR." },
  ko: { title: "PDF → 텍스트", description: "PDF를 업로드하지 않고 전체 또는 선택한 페이지에서 편집 가능한 텍스트를 인식합니다.", toolName: "PDF 텍스트 OCR", category: "로컬 영어·한국어 OCR로 PDF 페이지에서 편집 가능한 텍스트를 추출합니다." },
  ja: { title: "PDFからテキスト", description: "PDFをアップロードせず、全ページまたは選択ページから編集可能なテキストを認識します。", toolName: "PDFテキストOCR", category: "ローカルの英語・韓国語OCRでPDFページから編集可能なテキストを抽出します。" },
  es: { title: "PDF a texto", description: "Reconoce texto editable de todas las páginas o de una selección sin subir el PDF.", toolName: "OCR de PDF a texto", category: "Extrae texto editable de páginas PDF con OCR local en inglés y coreano." },
  de: { title: "PDF zu Text", description: "Erkennt bearbeitbaren Text auf allen oder ausgewählten Seiten, ohne die PDF hochzuladen.", toolName: "PDF-zu-Text-OCR", category: "Extrahiert bearbeitbaren Text aus PDF-Seiten mit lokaler englischer und koreanischer OCR." },
  fr: { title: "PDF en texte", description: "Reconnaît du texte modifiable dans toutes les pages ou une sélection sans téléverser le PDF.", toolName: "OCR PDF en texte", category: "Extrait du texte modifiable des pages PDF par OCR local anglais et coréen." },
};
const overrides = {
  ko: {
    eyebrow: "로컬 PDF OCR", drop: { title: "PDF 한 개 추가", description: "PDF를 놓거나 파일 선택기를 사용하세요.", choose: "PDF 선택", localTitle: "로컬에서 처리됩니다.", localBody: "PDF, 렌더링한 페이지, 인식된 텍스트는 이 기기에만 남습니다.", privacyLink: "개인정보 보호 방식" },
    source: { title: "원본 PDF", empty: "선택한 PDF가 없습니다.", selectedLabel: "선택한 원본 PDF", meta: "{pages}페이지 · {size}", replace: "PDF 교체", remove: "PDF 제거" }, warning: { large: "큰 PDF는 시간이 걸릴 수 있습니다. 로컬 OCR이 실행되는 동안 이 탭을 열어 두세요." },
    settings: { title: "텍스트 인식", pages: "페이지", all: "모든 페이지", selected: "선택한 페이지", range: "페이지 범위", rangePlaceholder: "1, 3-5", rangeHelp: "1, 3-5처럼 쉼표와 범위를 사용하세요.", language: "텍스트 언어", english: "영어", korean: "한국어", combined: "영어 + 한국어", recognize: "텍스트 인식", cancel: "취소", progress: "인식 진행률" },
    result: { searchableHint: "검색 가능한 PDF는 원래 OCR 배치를 사용하며 보이는 PDF 페이지를 그대로 유지합니다.", downloadSearchable: "검색 가능한 PDF 다운로드", title: "인식된 텍스트", description: "복사하거나 다운로드하기 전에 각 페이지를 확인하고 편집하세요.", page: "{page}페이지", pageLabel: "{page}페이지의 편집 가능한 인식 텍스트", copyPage: "페이지 복사", copyAll: "모두 복사", download: "TXT 다운로드" },
    status: { building: "검색 가능한 PDF를 로컬에서 만드는 중…", searchableDownloaded: "{name}을 다운로드했습니다.", preparing: "PDF를 로컬에서 준비하는 중…", ready: "PDF가 준비되었습니다. 페이지와 언어를 선택하세요.", cancelled: "인식을 취소했습니다. PDF는 준비 상태로 유지됩니다.", success: "인식이 완료되었습니다. 각 페이지를 편집할 수 있습니다.", copied: "인식된 텍스트를 모두 복사했습니다.", pageCopied: "{page}페이지를 복사했습니다.", downloaded: "{name}을 다운로드했습니다." },
    progress: { building: "{total}페이지 중 {page}페이지의 텍스트 레이어를 만드는 중…", saving: "검색 가능한 PDF를 로컬에 저장하는 중…", starting: "로컬 인식을 시작하는 중…", loading: "PDF를 로컬에서 불러오는 중…", "rendering-page": "{total}페이지 중 {page}페이지를 렌더링하는 중…", "recognizing-page": "{total}페이지 중 {page}페이지를 인식하는 중… {percent}%", complete: "인식을 마무리하는 중…" },
  },
  ja: {
    eyebrow: "ローカルPDF OCR", drop: { title: "PDFを1件追加", description: "PDFをドロップするか、ファイル選択を使用します。", choose: "PDFを選択", localTitle: "ローカル処理。", localBody: "PDF、描画ページ、認識テキストは端末外へ送信されません。", privacyLink: "プライバシーの仕組み" },
    source: { title: "元のPDF", empty: "PDFが未選択です。", selectedLabel: "選択した元のPDF", meta: "{pages}ページ · {size}", replace: "PDFを置換", remove: "PDFを削除" }, warning: { large: "大きなPDFは時間がかかることがあります。ローカルOCR中はこのタブを開いたままにしてください。" },
    settings: { title: "文字認識", pages: "ページ", all: "全ページ", selected: "選択したページ", range: "ページ範囲", rangePlaceholder: "1, 3-5", rangeHelp: "1, 3-5のようにカンマと範囲を使用します。", language: "テキスト言語", english: "英語", korean: "韓国語", combined: "英語 + 韓国語", recognize: "テキストを認識", cancel: "キャンセル", progress: "認識の進行状況" },
    result: { searchableHint: "検索可能PDFは元のOCR配置を使用し、表示されるPDFページを保持します。", downloadSearchable: "検索可能PDFをダウンロード", title: "認識したテキスト", description: "コピーまたはダウンロード前に各ページを確認・編集できます。", page: "ページ{page}", pageLabel: "ページ{page}の編集可能な認識テキスト", copyPage: "ページをコピー", copyAll: "すべてコピー", download: "TXTをダウンロード" },
    status: { building: "検索可能PDFをローカルで作成中…", searchableDownloaded: "{name}をダウンロードしました。", preparing: "PDFをローカルで準備中…", ready: "PDFの準備ができました。ページと言語を選択してください。", cancelled: "認識をキャンセルしました。PDFは準備済みです。", success: "認識が完了しました。各ページを編集できます。", copied: "認識テキストをすべてコピーしました。", pageCopied: "ページ{page}をコピーしました。", downloaded: "{name}をダウンロードしました。" },
    progress: { building: "{total}ページ中{page}ページのテキストレイヤーを作成中…", saving: "検索可能PDFをローカルに保存中…", starting: "ローカル認識を開始中…", loading: "PDFをローカルで読み込み中…", "rendering-page": "{total}ページ中{page}ページを描画中…", "recognizing-page": "{total}ページ中{page}ページを認識中… {percent}%", complete: "認識を完了中…" },
  },
  es: {
    eyebrow: "OCR local de PDF", drop: { title: "Añadir un PDF", description: "Suelta un PDF aquí o usa el selector.", choose: "Elegir PDF", localTitle: "Procesamiento local.", localBody: "El PDF, las páginas renderizadas y el texto reconocido permanecen en este dispositivo.", privacyLink: "Cómo funciona la privacidad" },
    source: { title: "PDF de origen", empty: "No hay ningún PDF seleccionado.", selectedLabel: "PDF de origen seleccionado", meta: "{pages} páginas · {size}", replace: "Reemplazar PDF", remove: "Quitar PDF" }, warning: { large: "Los PDF grandes pueden tardar. Mantén esta pestaña abierta mientras se ejecuta el OCR local." },
    settings: { title: "Reconocimiento", pages: "Páginas", all: "Todas las páginas", selected: "Páginas seleccionadas", range: "Rango de páginas", rangePlaceholder: "1, 3-5", rangeHelp: "Usa comas y rangos, por ejemplo 1, 3-5.", language: "Idioma del texto", english: "Inglés", korean: "Coreano", combined: "Inglés + coreano", recognize: "Reconocer texto", cancel: "Cancelar", progress: "Progreso del reconocimiento" },
    result: { searchableHint: "El PDF con búsqueda usa el diseño OCR original y conserva las páginas visibles.", downloadSearchable: "Descargar PDF con búsqueda", title: "Texto reconocido", description: "Revisa y edita cada página antes de copiarla o descargarla.", page: "Página {page}", pageLabel: "Texto reconocido editable de la página {page}", copyPage: "Copiar página", copyAll: "Copiar todo", download: "Descargar TXT" },
    status: { building: "Creando el PDF con búsqueda localmente…", searchableDownloaded: "Se descargó {name}.", preparing: "Preparando el PDF localmente…", ready: "PDF listo. Elige páginas e idioma para comenzar.", cancelled: "Reconocimiento cancelado. El PDF sigue listo.", success: "Reconocimiento terminado. Puedes editar cada página.", copied: "Se copió todo el texto reconocido.", pageCopied: "Página {page} copiada.", downloaded: "Se descargó {name}." },
    progress: { building: "Creando la capa de texto de la página {page} de {total}…", saving: "Guardando el PDF con búsqueda localmente…", starting: "Iniciando el reconocimiento local…", loading: "Cargando el PDF localmente…", "rendering-page": "Renderizando página {page} de {total}…", "recognizing-page": "Reconociendo página {page} de {total}… {percent}%", complete: "Finalizando el reconocimiento…" },
  },
  de: {
    eyebrow: "Lokale PDF-OCR", drop: { title: "Eine PDF hinzufügen", description: "PDF hier ablegen oder Dateiauswahl verwenden.", choose: "PDF auswählen", localTitle: "Lokale Verarbeitung.", localBody: "PDF, gerenderte Seiten und erkannter Text bleiben auf diesem Gerät.", privacyLink: "So funktioniert der Datenschutz" },
    source: { title: "Quell-PDF", empty: "Keine PDF ausgewählt.", selectedLabel: "Ausgewählte Quell-PDF", meta: "{pages} Seiten · {size}", replace: "PDF ersetzen", remove: "PDF entfernen" }, warning: { large: "Große PDFs können länger dauern. Lassen Sie diesen Tab während der lokalen OCR geöffnet." },
    settings: { title: "Erkennung", pages: "Seiten", all: "Alle Seiten", selected: "Ausgewählte Seiten", range: "Seitenbereich", rangePlaceholder: "1, 3-5", rangeHelp: "Kommas und Bereiche verwenden, zum Beispiel 1, 3-5.", language: "Textsprache", english: "Englisch", korean: "Koreanisch", combined: "Englisch + Koreanisch", recognize: "Text erkennen", cancel: "Abbrechen", progress: "Erkennungsfortschritt" },
    result: { searchableHint: "Die durchsuchbare PDF verwendet das ursprüngliche OCR-Layout und erhält die sichtbaren Seiten.", downloadSearchable: "Durchsuchbare PDF herunterladen", title: "Erkannter Text", description: "Jede Seite vor dem Kopieren oder Herunterladen prüfen und bearbeiten.", page: "Seite {page}", pageLabel: "Bearbeitbarer erkannter Text für Seite {page}", copyPage: "Seite kopieren", copyAll: "Alles kopieren", download: "TXT herunterladen" },
    status: { building: "Durchsuchbare PDF wird lokal erstellt…", searchableDownloaded: "{name} wurde heruntergeladen.", preparing: "PDF wird lokal vorbereitet…", ready: "PDF bereit. Seiten und Sprache auswählen.", cancelled: "Erkennung abgebrochen. Die PDF bleibt bereit.", success: "Erkennung abgeschlossen. Jede Seite kann bearbeitet werden.", copied: "Gesamten erkannten Text kopiert.", pageCopied: "Seite {page} kopiert.", downloaded: "{name} wurde heruntergeladen." },
    progress: { building: "Textebene für Seite {page} von {total} wird erstellt…", saving: "Durchsuchbare PDF wird lokal gespeichert…", starting: "Lokale Erkennung wird gestartet…", loading: "PDF wird lokal geladen…", "rendering-page": "Seite {page} von {total} wird gerendert…", "recognizing-page": "Seite {page} von {total} wird erkannt… {percent}%", complete: "Erkennung wird abgeschlossen…" },
  },
  fr: {
    eyebrow: "OCR PDF local", drop: { title: "Ajouter un PDF", description: "Déposez un PDF ici ou utilisez le sélecteur.", choose: "Choisir un PDF", localTitle: "Traitement local.", localBody: "Le PDF, les pages rendues et le texte reconnu restent sur cet appareil.", privacyLink: "Fonctionnement de la confidentialité" },
    source: { title: "PDF source", empty: "Aucun PDF sélectionné.", selectedLabel: "PDF source sélectionné", meta: "{pages} pages · {size}", replace: "Remplacer le PDF", remove: "Retirer le PDF" }, warning: { large: "Les PDF volumineux peuvent prendre du temps. Gardez cet onglet ouvert pendant l’OCR local." },
    settings: { title: "Reconnaissance", pages: "Pages", all: "Toutes les pages", selected: "Pages sélectionnées", range: "Plage de pages", rangePlaceholder: "1, 3-5", rangeHelp: "Utilisez des virgules et des plages, par exemple 1, 3-5.", language: "Langue du texte", english: "Anglais", korean: "Coréen", combined: "Anglais + coréen", recognize: "Reconnaître le texte", cancel: "Annuler", progress: "Progression de la reconnaissance" },
    result: { searchableHint: "Le PDF indexable utilise la disposition OCR source et conserve les pages visibles.", downloadSearchable: "Télécharger le PDF indexable", title: "Texte reconnu", description: "Vérifiez et modifiez chaque page avant de la copier ou de la télécharger.", page: "Page {page}", pageLabel: "Texte reconnu modifiable de la page {page}", copyPage: "Copier la page", copyAll: "Tout copier", download: "Télécharger le TXT" },
    status: { building: "Création locale du PDF indexable…", searchableDownloaded: "{name} téléchargé.", preparing: "Préparation locale du PDF…", ready: "PDF prêt. Choisissez les pages et la langue.", cancelled: "Reconnaissance annulée. Le PDF reste prêt.", success: "Reconnaissance terminée. Chaque page est modifiable.", copied: "Tout le texte reconnu a été copié.", pageCopied: "Page {page} copiée.", downloaded: "{name} téléchargé." },
    progress: { building: "Création du calque texte de la page {page} sur {total}…", saving: "Enregistrement local du PDF indexable…", starting: "Démarrage de la reconnaissance locale…", loading: "Chargement local du PDF…", "rendering-page": "Rendu de la page {page} sur {total}…", "recognizing-page": "Reconnaissance de la page {page} sur {total}… {percent}%", complete: "Finalisation de la reconnaissance…" },
  },
};
export const pdfToTextLocales = Object.fromEntries(Object.entries(localized).map(([language, value]) => [language, {
  metadata: { title: `${value.toolName} — Secure Tools`, description: value.description }, toolName: value.toolName,
  categoryDescription: value.category, copy: Object.fromEntries(Object.entries({ ...copy, title: value.title, description: value.description }).map(([key, item]) => [key, item && typeof item === "object" ? { ...item, ...(overrides[language]?.[key] || {}) } : (overrides[language]?.[key] || item)])),
}]));
