import { t } from "../../../js/i18n.js";
import { formatBytes, moveArrayItem } from "../../shared/file.js";
import { ACCEPTED_IMAGE_TYPES, selectImageQueueFiles, validateImageSignature } from "../../shared/image.js";
import { IMAGE_FORMATS } from "../../shared/image-output.js";
import { downloadBlob, requestSaveHandle, writeBlobToHandle } from "../../shared/save.js";
import { createResizePlan, resizeImages } from "./resize.js";

const elements = {
  input: document.querySelector("#file-input"), dropZone: document.querySelector("#drop-zone"), list: document.querySelector("#image-list"), empty: document.querySelector("#queue-empty"), count: document.querySelector("#image-count"),
  add: document.querySelector("#add-images"), clear: document.querySelector("#clear-images"), resize: document.querySelector("#resize-images"),
  form: document.querySelector("#resize-settings"), pixelFields: document.querySelector("#pixel-fields"), percentageField: document.querySelector("#percentage-field"), width: document.querySelector("#resize-width"), height: document.querySelector("#resize-height"), percentage: document.querySelector("#resize-percentage"), lock: document.querySelector("#aspect-ratio"), enlargement: document.querySelector("#allow-enlargement"),
  format: document.querySelector("#output-format"), quality: document.querySelector("#quality"), qualityField: document.querySelector("#quality-field"), qualityValue: document.querySelector("#quality-value"), progress: document.querySelector("#resize-progress"), result: document.querySelector("#result-summary"), status: document.querySelector("#tool-status"),
};
const state = { items: [], busy: false, status: null, result: null };
elements.input.accept = ACCEPTED_IMAGE_TYPES;
const message = (key, values = {}) => Object.entries(values).reduce((text, [name, value]) => text.replaceAll(`{${name}}`, String(value)), t(key));

function setStatus(key, values = {}, tone = "neutral") { state.status = key ? { key, values, tone } : null; elements.status.textContent = key ? message(key, values) : ""; elements.status.dataset.tone = tone; }
function clearResult(changed = false) { if (changed && state.result) setStatus("imageResize.status.settingsChanged"); state.result = null; elements.result.hidden = true; elements.result.textContent = ""; }
function rejectionReason(code) { return message(({ UNSUPPORTED_IMAGE: "imageToPdf.errors.unsupported", IMAGE_FILE_TOO_LARGE: "imageToPdf.errors.fileTooLarge", IMAGE_QUEUE_FILES_EXCEEDED: "imageToPdf.errors.queueFiles", IMAGE_SIGNATURE_INVALID: "imageToPdf.errors.signature", IMAGE_QUEUE_BYTES_EXCEEDED: "imageToPdf.errors.queueBytes" })[code] || "imageToPdf.errors.unsupported"); }
function setRejectedStatus(added, rejected) { state.status = { added, rejected, tone: "warning" }; const reasons = rejected.map(({ file, code }) => message("imageToPdf.status.rejectedItem", { name: file.name || "file", reason: rejectionReason(code) })).join("; "); elements.status.textContent = message("imageToPdf.status.addedWithReasons", { added, reasons }); elements.status.dataset.tone = "warning"; }
function actionButton(action, labelKey, symbol, disabled = false) { const button = document.createElement("button"); button.type = "button"; button.className = `queue-action queue-action--${action}`; button.dataset.action = action; button.setAttribute("aria-label", t(labelKey)); button.title = t(labelKey); button.textContent = symbol; button.disabled = disabled || state.busy; return button; }

function renderQueue() {
  elements.list.replaceChildren(); elements.empty.hidden = state.items.length > 0; elements.count.textContent = message("imageToPdf.queue.count", { count: state.items.length });
  elements.clear.disabled = state.busy || !state.items.length; elements.resize.disabled = state.busy || !state.items.length; elements.add.disabled = state.busy; elements.input.disabled = state.busy;
  elements.form.querySelectorAll("input, select").forEach((control) => { if (control !== elements.input) control.disabled = state.busy; });
  state.items.forEach((item, index) => { const row = document.createElement("li"); row.className = "queue-item"; row.dataset.id = item.id; const thumbnail = document.createElement("img"); thumbnail.className = "queue-thumbnail"; thumbnail.src = item.url; thumbnail.alt = message("imageToPdf.queue.previewAlt", { name: item.file.name }); const details = document.createElement("div"); details.className = "queue-details"; const name = document.createElement("strong"); name.className = "queue-name"; name.textContent = item.file.name; name.title = item.file.name; const meta = document.createElement("span"); meta.className = "queue-meta"; meta.textContent = message("imageResize.queue.meta", { size: formatBytes(item.file.size), format: item.format.toUpperCase(), position: index + 1 }); details.append(name, meta); const actions = document.createElement("div"); actions.className = "queue-actions"; actions.append(actionButton("up", "imageToPdf.queue.moveUp", "↑", index === 0), actionButton("down", "imageToPdf.queue.moveDown", "↓", index === state.items.length - 1), actionButton("remove", "imageToPdf.queue.remove", "×")); row.append(thumbnail, details, actions); elements.list.append(row); });
  updateControls();
}

async function addFiles(files) { const { accepted, rejected } = await selectImageQueueFiles(state.items.map((item) => item.file), files); for (const file of accepted) { const format = await validateImageSignature(file); state.items.push({ id: crypto.randomUUID?.() || `${Date.now()}-${Math.random()}`, file, format, url: URL.createObjectURL(file) }); } clearResult(); if (rejected.length) setRejectedStatus(accepted.length, rejected); else if (accepted.length) setStatus("imageToPdf.status.added", { count: accepted.length }, "success"); else setStatus("imageToPdf.errors.unsupported", {}, "error"); renderQueue(); }
function removeItem(index) { const [item] = state.items.splice(index, 1); if (item) URL.revokeObjectURL(item.url); clearResult(); setStatus("imageToPdf.status.removed"); renderQueue(); }
function moveItem(index, offset) { const next = moveArrayItem(state.items, index, offset); if (next < 0) return; clearResult(); setStatus("imageToPdf.status.reordered"); renderQueue(); elements.list.querySelector(`[data-id="${state.items[next].id}"] [data-action="${offset < 0 ? "up" : "down"}"]`)?.focus(); }
function clearItems() { state.items.forEach((item) => URL.revokeObjectURL(item.url)); state.items.length = 0; elements.input.value = ""; clearResult(); setStatus("imageToPdf.status.cleared"); renderQueue(); }
function selectedMode() { return elements.form.elements["resize-mode"].value; }
function updateControls() { const percentage = selectedMode() === "percentage"; elements.pixelFields.hidden = percentage; elements.percentageField.hidden = !percentage; elements.lock.closest("label").hidden = percentage; const originalHasLossy = !state.items.length || state.items.some((item) => item.format !== "png"); const showQuality = elements.format.value !== "png" && (elements.format.value !== "original" || originalHasLossy); elements.qualityField.hidden = !showQuality; elements.quality.disabled = state.busy || !showQuality; }
function settings() { return { mode: selectedMode(), width: elements.width.value, height: elements.height.value, percentage: elements.percentage.value, lockAspectRatio: elements.lock.checked, allowEnlargement: elements.enlargement.checked }; }
function errorMessage(error) { const key = ({ NO_FILES: "imageResize.errors.noFiles", RESIZE_MODE_INVALID: "imageResize.errors.mode", RESIZE_DIMENSION_REQUIRED: "imageResize.errors.dimensionRequired", RESIZE_DIMENSION_INVALID: "imageResize.errors.dimensionInvalid", RESIZE_PERCENTAGE_INVALID: "imageResize.errors.percentage", IMAGE_DIMENSION_EXCEEDED: "imageResize.errors.dimensionLimit", IMAGE_PIXELS_EXCEEDED: "imageResize.errors.pixelLimit", RESIZE_JOB_PIXELS_EXCEEDED: "imageResize.errors.jobPixels", IMAGE_FORMAT_INVALID: "imageResize.errors.format", IMAGE_DECODE_FAILED: "imageToPdf.errors.decode", IMAGE_ENCODER_FAILED: "imageConverter.errors.encoder", CANVAS_UNAVAILABLE: "imageConverter.errors.canvas", ARCHIVE_LIBRARY_UNAVAILABLE: "imageConverter.errors.archiveLibrary", ARCHIVE_GENERATION_FAILED: "imageConverter.errors.archive" })[error.code] || "imageResize.errors.failure"; return message(key, { name: error.fileName || "" }); }

async function resizeQueue() {
  if (!state.items.length || state.busy) { setStatus("imageResize.errors.noFiles", {}, "error"); return; }
  const files = state.items.map((item) => item.file); const options = { files, sourceFormats: state.items.map((item) => item.format), outputFormat: elements.format.value, quality: Number(elements.quality.value), settings: settings() }; let plan;
  try { plan = createResizePlan(options); } catch (error) { elements.status.textContent = errorMessage(error); elements.status.dataset.tone = "error"; return; }
  const multiple = files.length > 1; const filename = multiple ? plan.names.archive : plan.names.entries[0]; const outputType = multiple ? "application/zip" : IMAGE_FORMATS[plan.formats[0]].mimeType; const extension = multiple ? ".zip" : `.${IMAGE_FORMATS[plan.formats[0]].extension}`; let fileHandle = null;
  if ("showSaveFilePicker" in window) { try { fileHandle = await requestSaveHandle(window, { suggestedName: filename, description: t(multiple ? "imageResize.settings.zipFile" : "imageResize.settings.imageFile"), mimeType: outputType, extension }); } catch (error) { setStatus(error.name === "AbortError" ? "imageResize.status.saveCancelled" : "imageConverter.errors.save", {}, error.name === "AbortError" ? "neutral" : "error"); return; } }
  state.busy = true; elements.progress.hidden = false; elements.progress.max = files.length; elements.progress.value = 0; setStatus("imageResize.status.resizing"); renderQueue(); let resized = false;
  try { const result = await resizeImages({ files, outputFormat: options.outputFormat, quality: options.quality, settings: options.settings, JSZip: window.JSZip, onProgress(completed, total) { elements.progress.value = completed; setStatus("imageResize.status.progress", { completed, total }); } }); resized = true; if (fileHandle) await writeBlobToHandle(fileHandle, result.blob); else downloadBlob(result.blob, result.filename); state.result = result.results; if (result.results.length === 1) { const dimensions = result.results[0]; elements.result.textContent = message("imageResize.status.dimensions", { originalWidth: dimensions.original.width, originalHeight: dimensions.original.height, width: dimensions.output.width, height: dimensions.output.height }); elements.result.hidden = false; } setStatus(fileHandle ? "imageResize.status.saved" : "imageResize.status.downloaded", { name: result.filename, count: result.entries.length }, "success"); } catch (error) { console.error("Image resize failed", error); elements.status.textContent = resized && !error.code ? message("imageConverter.errors.save") : errorMessage(error); elements.status.dataset.tone = "error"; state.status = null; } finally { state.busy = false; elements.progress.hidden = true; renderQueue(); }
}

elements.add.addEventListener("click", () => elements.input.click()); elements.input.addEventListener("change", (event) => { void addFiles([...event.target.files]); elements.input.value = ""; }); elements.clear.addEventListener("click", clearItems); elements.resize.addEventListener("click", resizeQueue); elements.quality.addEventListener("input", () => { elements.qualityValue.textContent = `${Math.round(Number(elements.quality.value) * 100)}%`; clearResult(true); });
elements.form.addEventListener("change", (event) => { if (event.target !== elements.quality) clearResult(true); updateControls(); }); elements.form.addEventListener("input", (event) => { if ([elements.width, elements.height, elements.percentage].includes(event.target)) clearResult(true); });
elements.list.addEventListener("click", (event) => { const button = event.target.closest("button[data-action]"); if (!button) return; const index = state.items.findIndex((item) => item.id === button.closest("[data-id]").dataset.id); if (button.dataset.action === "remove") removeItem(index); if (button.dataset.action === "up") moveItem(index, -1); if (button.dataset.action === "down") moveItem(index, 1); });
["dragenter", "dragover"].forEach((type) => elements.dropZone.addEventListener(type, (event) => { event.preventDefault(); if (!state.busy) elements.dropZone.dataset.dragging = "true"; })); ["dragleave", "drop"].forEach((type) => elements.dropZone.addEventListener(type, (event) => { event.preventDefault(); delete elements.dropZone.dataset.dragging; })); elements.dropZone.addEventListener("drop", (event) => { if (!state.busy) void addFiles([...event.dataTransfer.files]); });
document.addEventListener("securetools:languagechange", () => { renderQueue(); if (state.status?.rejected) setRejectedStatus(state.status.added, state.status.rejected); else if (state.status) setStatus(state.status.key, state.status.values, state.status.tone); }); window.addEventListener("beforeunload", () => state.items.forEach((item) => URL.revokeObjectURL(item.url)));
elements.qualityValue.textContent = `${Math.round(Number(elements.quality.value) * 100)}%`; renderQueue();
